const $=s=>document.querySelector(s), STORE='terrorland-config-v1', SAVE='terrorland-save-v1';
const AUTH_HASH='44ae83e89a37b6ffb61a0bc39d546c0663fa8b681a0a78ec4e990c80dc94298e';
let config,state,timer,paused=false;
const slots=['Main Hand','Off Hand','Head','Body','Hands','Feet','Trinket'];
const hash=async value=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))].map(x=>x.toString(16).padStart(2,'0')).join('');
const roll=([a,b])=>a+Math.floor(Math.random()*(b-a+1));
const log=(message,kind='')=>{const p=document.createElement('p');p.textContent=message;if(kind)p.className=kind;$('#log').prepend(p)};
function validate(c){if(!c||!c.hero||!Array.isArray(c.floors)||!c.floors.length)throw Error('hero and at least one floor are required');if(!c.loot?.rarities?.length)throw Error('loot.rarities is required');c.floors.forEach((f,i)=>{if(!f.name||!f.enemies?.length)throw Error(`Floor ${i+1} needs a name and enemies`)}) ;return c}
async function loadConfig(){const base=await fetch('game.json').then(r=>r.json());const saved=localStorage.getItem(STORE);config=validate(saved?JSON.parse(saved):base)}
function freshState(){return{floor:0,enemy:0,heroHp:config.hero.maxHealth,enemyHp:0,portals:config.hero.portals,equipment:{},loot:[],running:false,wins:0}}
function save(){localStorage.setItem(SAVE,JSON.stringify(state))}
function enemy(){return config.floors[state.floor]?.enemies[state.enemy]}
function power(){return Object.values(state.equipment).reduce((n,x)=>n+x.power,0)}
function spawn(){const e=enemy();if(!e)return victory();state.enemyHp=e.health;log(`${e.name} emerges.`);render()}
function start(){if(state.running)return;state.running=true;paused=false;$('#startBtn').textContent='Expedition Running';$('#startBtn').disabled=true;$('#pauseBtn').disabled=false;$('#retreatBtn').disabled=state.portals<1;if(!state.enemyHp)spawn();timer=setInterval(tick,config.tickMs);log('The Vanguard enters the Silt Tombs.');save();render()}
function tick(){if(paused||!state.running)return;const e=enemy();if(!e)return;animate('#heroCard','attack');const dealt=roll(config.hero.damage)+power();state.enemyHp=Math.max(0,state.enemyHp-dealt);log(`Vanguard strikes ${e.name} for ${dealt}.`);if(state.enemyHp<=0){defeatEnemy(e);return}animate('#enemyCard','attack');const hurt=Math.max(1,roll(e.damage)-config.hero.armor-Math.floor(power()/5));state.heroHp=Math.max(0,state.heroHp-hurt);log(`${e.name} hits for ${hurt}.`);if(state.heroHp<=0){stop();log('The Vanguard falls and wakes in Emberrest.');state.floor=0;state.enemy=0;state.heroHp=config.hero.maxHealth;state.enemyHp=0;$('#startBtn').textContent='Begin Again';save()}render()}
function defeatEnemy(e){log(`${e.name} is defeated.`);if(Math.random()<config.loot.dropChance||e.boss)dropLoot(e.boss);state.enemy++;if(state.enemy>=config.floors[state.floor].enemies.length){state.floor++;state.enemy=0;state.heroHp=Math.min(config.hero.maxHealth,state.heroHp+30);if(state.floor>=config.floors.length){victory();return}log(`Floor cleared. Descending to ${config.floors[state.floor].name}.`)}spawn();save()}
function weighted(){let total=config.loot.rarities.reduce((n,r)=>n+r.weight,0),x=Math.random()*total;return config.loot.rarities.find(r=>(x-=r.weight)<=0)||config.loot.rarities[0]}
function dropLoot(boss=false){const rarity=boss?config.loot.rarities.at(-1):weighted(),slot=config.loot.slots[Math.floor(Math.random()*config.loot.slots.length)],base=config.loot.bases[config.loot.slots.indexOf(slot)%config.loot.bases.length],item={name:`${rarity.name} ${base}`,slot,power:roll(rarity.power),rarity:rarity.id};state.loot.unshift(item);if(!state.equipment[slot]||item.power>state.equipment[slot].power){state.equipment[slot]=item;log(`Equipped ${item.name} (+${item.power}).`,`rarity-${item.rarity}`)}else log(`Found ${item.name} (+${item.power}).`,`rarity-${item.rarity}`)}
function victory(){stop();state.wins++;state.enemyHp=0;log('The Mummy Queen falls. The tomb yields to you!','rarity-mythic');$('#startBtn').textContent='Victory — Run Again';$('#startBtn').disabled=false;save();render()}
function stop(){clearInterval(timer);state.running=false;$('#pauseBtn').disabled=true;$('#retreatBtn').disabled=true}
function retreat(){if(state.portals<1||!state.running)return;state.portals--;stop();state.heroHp=config.hero.maxHealth;state.enemyHp=0;$('#startBtn').textContent='Return to the Tombs';$('#startBtn').disabled=false;log('A portal tears open. The Vanguard retreats to Emberrest.');save();render()}
function animate(sel,c){const el=$(sel);el.classList.remove(c);void el.offsetWidth;el.classList.add(c);setTimeout(()=>el.classList.remove(c),300)}
function render(){const e=enemy(),floor=config.floors[state.floor];$('#floorName').textContent=floor?.name||(state.wins?'Tombs Conquered':'Emberrest');$('#progress').textContent=floor?`Floor ${state.floor+1}/${config.floors.length} · Foe ${state.enemy+1}/${floor.enemies.length}`:'Expedition complete';$('#heroName').textContent=config.hero.name;$('#heroHealth').style.width=`${100*state.heroHp/config.hero.maxHealth}%`;$('#heroStats').textContent=`${state.heroHp}/${config.hero.maxHealth} HP · ${config.hero.damage.join('–')} damage`;$('#enemyName').textContent=e?.name||'No foe';$('#enemyIcon').textContent=e?.icon||'·';$('#enemyHealth').style.width=e?`${100*state.enemyHp/e.health}%`:'0%';$('#enemyStats').textContent=e?`${state.enemyHp}/${e.health} HP · ${e.damage.join('–')} damage`:'';$('#portalCount').textContent=`×${state.portals}`;$('#power').textContent=`Power ${power()}`;$('#lootCount').textContent=`${state.loot.length} found`;$('#equipment').innerHTML=slots.map(s=>`<div class="slot"><small>${s}</small><b class="rarity-${state.equipment[s]?.rarity||'common'}">${state.equipment[s]?.name||'Empty'}${state.equipment[s]?` +${state.equipment[s].power}`:''}</b></div>`).join('');$('#loot').innerHTML=state.loot.slice(0,15).map(x=>`<p class="rarity-${x.rarity}">${x.name} · ${x.slot} · +${x.power}</p>`).join('')||'<p>No treasures yet.</p>'}
function reset(){stop();state=freshState();localStorage.removeItem(SAVE);$('#startBtn').textContent='Begin Expedition';$('#startBtn').disabled=false;log('A new fate has been written.');render()}
$('#startBtn').onclick=start;$('#pauseBtn').onclick=()=>{paused=!paused;$('#pauseBtn').textContent=paused?'Resume':'Pause';log(paused?'Time stops.':'Time resumes.')};$('#retreatBtn').onclick=retreat;$('#resetBtn').onclick=reset;$('#clearLog').onclick=()=>$('#log').innerHTML='';
$('#authorBtn').onclick=()=>{$('#authorDialog').showModal();$('#password').focus()};
$('#unlockBtn').onclick=async()=>{if(await hash($('#password').value)!==AUTH_HASH){$('#authError').textContent='The gate remains sealed.';return}$('#unlockPane').hidden=true;$('#editorPane').hidden=false;$('#jsonEditor').value=JSON.stringify(config,null,2);$('#password').value=''};
function readEditor(){return validate(JSON.parse($('#jsonEditor').value))}
$('#applyJson').onclick=()=>{try{config=readEditor();reset();$('#editorStatus').textContent='Valid configuration applied to this session.'}catch(e){$('#editorStatus').textContent=`Error: ${e.message}`}};
$('#saveJson').onclick=()=>{try{config=readEditor();localStorage.setItem(STORE,JSON.stringify(config));reset();$('#editorStatus').textContent='Saved in this browser and applied.'}catch(e){$('#editorStatus').textContent=`Error: ${e.message}`}};
$('#restoreJson').onclick=()=>{localStorage.removeItem(STORE);localStorage.removeItem(SAVE);location.reload()};
$('#exportJson').onclick=()=>{try{const blob=new Blob([JSON.stringify(readEditor(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='terrorland-game.json';a.click();URL.revokeObjectURL(a.href)}catch(e){$('#editorStatus').textContent=`Error: ${e.message}`}};
await loadConfig();try{state=JSON.parse(localStorage.getItem(SAVE))||freshState()}catch{state=freshState()}state.running=false;$('#version').textContent=`build ${document.lastModified.slice(0,10)}`;render();log('TerrorLand is ready.');
