const $=s=>document.querySelector(s),STORE='terrorland-config-v2',SAVE='terrorland-save-v2';
const AUTH_HASH='44ae83e89a37b6ffb61a0bc39d546c0663fa8b681a0a78ec4e990c80dc94298e';
let config,state,timer,paused=false;
const hash=async value=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))].map(x=>x.toString(16).padStart(2,'0')).join('');
const roll=([a,b])=>a+Math.floor(Math.random()*(b-a+1)),pick=a=>a[Math.floor(Math.random()*a.length)];
const log=(m,k='')=>{const p=document.createElement('p');p.textContent=m;if(k)p.className=k;$('#log').prepend(p)};
function validate(c){if(!c?.hero||!Number.isInteger(c.floorCount)||c.floorCount<1)throw Error('hero and a positive integer floorCount are required');if(!c.floorNames?.adjectives?.length||!c.floorNames?.nouns?.length)throw Error('floor name lists are required');if(!c.enemies?.length||!c.loot?.affixes?.length||!c.stats?.length)throw Error('enemies, affixes, and stats are required');const ids=new Set(c.stats.map(x=>x.id));c.loot.affixes.forEach((a,i)=>{if(!a.name||!a.types?.length||!ids.has(a.effect?.stat))throw Error(`Affix ${i+1} is invalid`)});return c}
async function loadConfig(){const base=await fetch('game.json').then(r=>r.json());const saved=localStorage.getItem(STORE);config=validate(saved?JSON.parse(saved):base)}
function generateRun(){return Array.from({length:config.floorCount},(_,i)=>{const n=i+1,count=n+roll([1,n*2]),scale=1+i*.28,enemies=Array.from({length:count},()=>{const b=pick(config.enemies);return{...b,health:Math.round(b.health*scale),damage:b.damage.map(x=>Math.round(x*scale))}});if(n===config.floorCount)enemies.push({...config.boss});return{name:`${pick(config.floorNames.adjectives)} ${pick(config.floorNames.nouns)}`,enemies}})}
function freshState(){return{configVersion:config.version,floor:0,enemy:0,heroHp:config.hero.maxHealth,enemyHp:0,portals:config.hero.portals,equipment:{},loot:[],run:generateRun(),running:false,wins:0}}
function save(){localStorage.setItem(SAVE,JSON.stringify(state))}function floor(){return state.run[state.floor]}function enemy(){return floor()?.enemies[state.enemy]}function slots(){return Object.keys(config.loot.itemBases)}
function statTotals(){const o={};Object.values(state.equipment).forEach(x=>x.effects.forEach(e=>o[e.stat]=(o[e.stat]||0)+e.value));return o}function stat(id){return statTotals()[id]||0}function maxHealth(){return config.hero.maxHealth+stat('max_health')}function power(){return Object.values(state.equipment).reduce((n,x)=>n+x.power,0)}
function spawn(){const e=enemy();if(!e)return victory();state.enemyHp=e.health;log(`${e.name} emerges.`);render()}
function start(){if(state.running)return;state.running=true;paused=false;$('#startBtn').textContent='Expedition Running';$('#startBtn').disabled=true;$('#pauseBtn').disabled=false;$('#retreatBtn').disabled=state.portals<1;if(!state.enemyHp)spawn();timer=setInterval(tick,Math.max(180,config.tickMs*(1-stat('attack_speed')/100)));log('The Vanguard enters the Silt Tombs.');save();render()}
function heroDamage(){const t=statTotals(),elemental=['fire_damage','cold_damage','lightning_damage','poison_damage'].reduce((n,k)=>n+(t[k]||0),0);let v=roll(config.hero.damage)+(t.damage_flat||0)+elemental;v=Math.round(v*(1+(t.damage_percent||0)/100));if(Math.random()<(t.critical_chance||0)/100){v=Math.round(v*(1.5+(t.critical_damage||0)/100));log('Critical strike!')}return v}
function tick(){if(paused||!state.running)return;const e=enemy();if(!e)return;animate('#heroCard','attack');let dealt=heroDamage();if(state.enemyHp/e.health<=.2&&Math.random()<stat('execute_chance')/100){dealt=state.enemyHp;log('Execution!')}state.enemyHp=Math.max(0,state.enemyHp-dealt);const heal=stat('life_on_hit');if(heal)state.heroHp=Math.min(maxHealth(),state.heroHp+heal);log(`Vanguard strikes ${e.name} for ${dealt}.`);if(state.enemyHp<=0){defeatEnemy(e);return}animate('#enemyCard','attack');if(Math.random()<stat('dodge_chance')/100){log('Vanguard dodges the attack.');render();return}let hurt=Math.max(1,roll(e.damage)-config.hero.armor-stat('armor_flat'));if(Math.random()<stat('block_chance')/100){hurt=Math.max(0,Math.floor(hurt/2));log('Vanguard blocks!')}hurt=Math.round(hurt*(1-stat('damage_reduction')/100));state.heroHp=Math.max(0,state.heroHp-hurt);log(`${e.name} hits for ${hurt}.`);const thorns=stat('thorns');if(thorns){state.enemyHp=Math.max(0,state.enemyHp-thorns);log(`${e.name} suffers ${thorns} retaliation damage.`)}if(state.heroHp<=0){stop();log('The Vanguard falls and wakes in Emberrest.');state.floor=0;state.enemy=0;state.heroHp=maxHealth();state.enemyHp=0;state.run=generateRun();$('#startBtn').textContent='Begin Again';$('#startBtn').disabled=false;save()}else if(state.enemyHp<=0)defeatEnemy(e);render()}
function defeatEnemy(e){log(`${e.name} is defeated.`);if(Math.random()<config.loot.dropChance||e.boss)dropLoot(e.boss);state.enemy++;if(state.enemy>=floor().enemies.length){state.floor++;state.enemy=0;state.heroHp=Math.min(maxHealth(),state.heroHp+30+stat('life_regen'));if(state.floor>=state.run.length){victory();return}log(`Floor cleared. Descending to ${floor().name}.`)}spawn();save()}
function affix(type){return pick(config.loot.affixes.filter(a=>a.types.includes(type)))}function rolledAffix(type){const a=affix(type);return{name:a.name,type,effect:{stat:a.effect.stat,value:roll([a.effect.min,a.effect.max])}}}function effectLabel(e){return`+${e.value} ${config.stats.find(s=>s.id===e.stat)?.label||e.stat}`}
function dropLoot(boss=false){const slot=pick(slots()),base=pick(config.loot.itemBases[slot]),parts=[],prefix=(boss||Math.random()<config.loot.prefixChance)?rolledAffix('prefix'):null,suffix=(boss||Math.random()<config.loot.suffixChance)?rolledAffix('suffix'):null,extra=(prefix||suffix)&&Math.random()<config.loot.extraChance?rolledAffix('extra'):null;if(extra)parts.push(extra);if(prefix)parts.push(prefix);if(suffix)parts.push(suffix);const name=`${extra?extra.name+' ':''}${prefix?prefix.name+' ':''}${base}${suffix?' of '+suffix.name:''}`,effects=parts.map(x=>x.effect),scores=new Map(config.stats.map(s=>[s.id,s.score])),item={name,slot,effects,affixes:parts,power:Math.max(1,Math.round(effects.reduce((n,e)=>n+e.value*(scores.get(e.stat)||1),0))),rarity:config.loot.rarities.find(r=>r.affixCount===parts.length)?.id||'common'};state.loot.unshift(item);if(!state.equipment[slot]||item.power>state.equipment[slot].power){state.equipment[slot]=item;state.heroHp=Math.min(maxHealth(),state.heroHp+stat('max_health'));log(`Equipped ${item.name}: ${effects.map(effectLabel).join(', ')||'no affixes'}.`,`rarity-${item.rarity}`)}else log(`Found ${item.name}: ${effects.map(effectLabel).join(', ')||'no affixes'}.`,`rarity-${item.rarity}`)}
function victory(){stop();state.wins++;state.enemyHp=0;log('The Mummy Queen falls. The tomb yields to you!','rarity-mythic');$('#startBtn').textContent='Victory — New Run';$('#startBtn').disabled=false;save();render()}function stop(){clearInterval(timer);state.running=false;$('#pauseBtn').disabled=true;$('#retreatBtn').disabled=true}
function retreat(){if(state.portals<1||!state.running)return;state.portals--;stop();state.heroHp=maxHealth();state.enemyHp=0;state.run=generateRun();state.floor=0;state.enemy=0;$('#startBtn').textContent='Return to the Tombs';$('#startBtn').disabled=false;log('A portal tears open. The Vanguard retreats to Emberrest.');save();render()}function animate(sel,c){const el=$(sel);el.classList.remove(c);void el.offsetWidth;el.classList.add(c);setTimeout(()=>el.classList.remove(c),300)}
function render(){const e=enemy(),f=floor(),hp=maxHealth();$('#floorName').textContent=f?.name||(state.wins?'Tombs Conquered':'Emberrest');$('#progress').textContent=f?`Floor ${state.floor+1}/${state.run.length} · Foe ${state.enemy+1}/${f.enemies.length}`:'Expedition complete';$('#heroName').textContent=config.hero.name;$('#heroHealth').style.width=`${100*state.heroHp/hp}%`;$('#heroStats').textContent=`${state.heroHp}/${hp} HP · ${config.hero.damage.join('–')} base damage`;$('#enemyName').textContent=e?.name||'No foe';$('#enemyIcon').textContent=e?.icon||'·';$('#enemyHealth').style.width=e&&state.enemyHp?`${100*state.enemyHp/e.health}%`:'0%';$('#enemyStats').textContent=e&&state.enemyHp?`${state.enemyHp}/${e.health} HP · ${e.damage.join('–')} damage`:'Awaiting expedition';$('#portalCount').textContent=`×${state.portals}`;$('#power').textContent=`Power ${power()}`;$('#lootCount').textContent=`${state.loot.length} found`;$('#equipment').innerHTML=slots().map(s=>{const x=state.equipment[s],tip=x?.effects.map(effectLabel).join(' · ')||'';return`<div class="slot" title="${tip}"><small>${s}</small><b class="rarity-${x?.rarity||'common'}">${x?.name||'Empty'}${x?` · ${tip}`:''}</b></div>`}).join('');$('#loot').innerHTML=state.loot.slice(0,15).map(x=>`<p class="rarity-${x.rarity}">${x.name} · ${x.slot} · ${x.effects.map(effectLabel).join(', ')||'Unadorned'}</p>`).join('')||'<p>No treasures yet.</p>'}
function reset(){stop();state=freshState();localStorage.removeItem(SAVE);$('#startBtn').textContent='Begin Expedition';$('#startBtn').disabled=false;log('A new fate has been written.');render()}
$('#startBtn').onclick=start;$('#pauseBtn').onclick=()=>{paused=!paused;$('#pauseBtn').textContent=paused?'Resume':'Pause';log(paused?'Time stops.':'Time resumes.')};$('#retreatBtn').onclick=retreat;$('#resetBtn').onclick=reset;$('#clearLog').onclick=()=>$('#log').innerHTML='';$('#authorBtn').onclick=()=>{$('#authorDialog').showModal();$('#password').focus()};
$('#unlockBtn').onclick=async()=>{if(await hash($('#password').value)!==AUTH_HASH){$('#authError').textContent='The gate remains sealed.';return}$('#unlockPane').hidden=true;$('#editorPane').hidden=false;$('#jsonEditor').value=JSON.stringify(config,null,2);$('#password').value=''};function readEditor(){return validate(JSON.parse($('#jsonEditor').value))}
$('#applyJson').onclick=()=>{try{config=readEditor();reset();$('#editorStatus').textContent='Valid configuration applied to this session.'}catch(e){$('#editorStatus').textContent=`Error: ${e.message}`}};$('#saveJson').onclick=()=>{try{config=readEditor();localStorage.setItem(STORE,JSON.stringify(config));reset();$('#editorStatus').textContent='Saved in this browser and applied.'}catch(e){$('#editorStatus').textContent=`Error: ${e.message}`}};$('#restoreJson').onclick=()=>{localStorage.removeItem(STORE);localStorage.removeItem(SAVE);location.reload()};$('#exportJson').onclick=()=>{try{const blob=new Blob([JSON.stringify(readEditor(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='terrorland-game.json';a.click();URL.revokeObjectURL(a.href)}catch(e){$('#editorStatus').textContent=`Error: ${e.message}`}};
await loadConfig();try{state=JSON.parse(localStorage.getItem(SAVE))||freshState();if(state.configVersion!==config.version||!state.run)state=freshState()}catch{state=freshState()}state.running=false;$('#version').textContent=`build ${document.lastModified.slice(0,10)}`;render();log('TerrorLand is ready.');
